"use client";
import {FormEvent,useState} from "react";

export default function RecruiterPage(){
 const [form,setForm]=useState({title:"",description:"",companyName:"",website:"",location:"",city:"",region:"",country:"India",remote:false,workplaceType:"On-site",salaryMin:"",salaryMax:"",currency:"INR",experienceMin:"",experienceMax:"",applicationUrl:""});
 const [busy,setBusy]=useState(false); const [result,setResult]=useState<{jobId?:string;matchedCandidates?:number;topMatches?:Array<{name:string|null;score:number;reasons:string[]}>;error?:string}|null>(null);
 const set=(key:string,value:string|boolean)=>setForm(f=>({...f,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setResult(null);const r=await fetch("/api/recruiter/jobs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,salaryMin:form.salaryMin?Number(form.salaryMin):undefined,salaryMax:form.salaryMax?Number(form.salaryMax):undefined,experienceMin:form.experienceMin?Number(form.experienceMin):undefined,experienceMax:form.experienceMax?Number(form.experienceMax):undefined})});const d=await r.json();setResult(r.ok?d:{error:d.error||"Could not post job"});setBusy(false);}
 return <main className="min-h-screen px-5 py-10 sm:px-8"><div className="mx-auto max-w-6xl">
  <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="section-kicker">RECRUITER INTELLIGENCE</div><h1 className="mt-2 text-4xl font-semibold tracking-tight">Post a job. Let AI find the people.</h1><p className="mt-3 max-w-2xl text-white/40">Every native job is published into HiddenHire and automatically matched against active candidate profiles.</p></div><a href="/" className="secondary-button">Candidate search</a></div>
  <div className="mt-10 grid gap-6 lg:grid-cols-[1.5fr_.8fr]">
   <form onSubmit={submit} className="search-panel space-y-5">
    <div className="grid gap-5 md:grid-cols-2"><Field label="Job title"><input required value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Finance Manager"/></Field><Field label="Company"><input required value={form.companyName} onChange={e=>set("companyName",e.target.value)} placeholder="Your company"/></Field><Field label="Company website"><input value={form.website} onChange={e=>set("website",e.target.value)} placeholder="https://company.com"/></Field><Field label="Application URL"><input value={form.applicationUrl} onChange={e=>set("applicationUrl",e.target.value)} placeholder="https://company.com/apply"/></Field></div>
    <Field label="Job description"><textarea required rows={9} value={form.description} onChange={e=>set("description",e.target.value)} placeholder="Responsibilities, requirements, skills, experience…"/></Field>
    <div className="grid gap-5 md:grid-cols-3"><Field label="Country"><input value={form.country} onChange={e=>set("country",e.target.value)}/></Field><Field label="City"><input value={form.city} onChange={e=>set("city",e.target.value)}/></Field><Field label="Region / State"><input value={form.region} onChange={e=>set("region",e.target.value)}/></Field></div>
    <div className="grid gap-5 md:grid-cols-4"><Field label="Min salary"><input type="number" min="0" value={form.salaryMin} onChange={e=>set("salaryMin",e.target.value)}/></Field><Field label="Max salary"><input type="number" min="0" value={form.salaryMax} onChange={e=>set("salaryMax",e.target.value)}/></Field><Field label="Currency"><select value={form.currency} onChange={e=>set("currency",e.target.value)}><option>INR</option><option>USD</option><option>GBP</option><option>EUR</option></select></Field><Field label="Workplace"><select value={form.workplaceType} onChange={e=>set("workplaceType",e.target.value)}><option>On-site</option><option>Hybrid</option><option>Remote</option></select></Field></div>
    <label className="toggle-row"><input type="checkbox" checked={form.remote} onChange={e=>set("remote",e.target.checked)}/><span className="toggle"/><span><strong>Remote role</strong><small>Allow HiddenHire to match candidates who can work remotely</small></span></label>
    {result?.error&&<div className="rounded-xl border border-red-400/10 bg-red-400/[0.04] p-4 text-sm text-red-200/80">{result.error}</div>}
    <button className="primary-button" disabled={busy}>{busy?"Publishing and matching…":"Publish + find candidates"} <span>→</span></button>
   </form>
   <aside className="feature-card h-fit"><div className="section-kicker">AI CANDIDATE MATCH</div><div className="mt-3 text-5xl font-semibold">↗</div><h2 className="mt-3 text-xl font-semibold">Reverse matching</h2><p className="mt-2 text-sm leading-6 text-white/40">Instead of waiting for applications, HiddenHire evaluates active candidate profiles against your job and stores explainable match scores.</p>{result?.jobId&&<div className="mt-6 rounded-xl border border-emerald-300/10 bg-emerald-300/[0.035] p-4"><div className="text-xs uppercase tracking-[.14em] text-emerald-200/60">Published</div><div className="mt-2 text-2xl font-semibold">{result.matchedCandidates??0}</div><div className="text-xs text-white/35">candidate matches generated</div></div>}</aside>
  </div>
  {result?.topMatches?.length?<section className="mt-10"><div className="section-kicker">TOP MATCHES</div><div className="mt-4 grid gap-4 md:grid-cols-2">{result.topMatches.map((m,i)=><div className="job-card" key={m.candidateId??i}><div className="flex items-center justify-between"><div><div className="text-xs text-white/35">Candidate</div><h3 className="mt-1 text-lg font-semibold">{m.name||"Hidden candidate"}</h3></div><div className="score-ring" style={{"--score":(m.score*3.6)+"deg"} as React.CSSProperties}><strong>{m.score}</strong><span>MATCH</span></div></div><ul className="mt-5 space-y-2 text-sm text-white/55">{m.reasons.slice(0,3).map(x=><li key={x}><span className="mr-2 text-cyan-300">✓</span>{x}</li>)}</ul></div>)}</div></section>:null}
 </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-medium uppercase tracking-[.12em] text-white/40">{label}<div className="mt-2">{children}</div></label>}
