"use client";
import { useEffect, useState } from "react";
type Appeal={id:string;case_id:string;job_id:string;recruiter_id:string;reason:string;status:string;submitted_at:string;resolution?:string|null};
export default function ModerationAdminPage(){
 const [appeals,setAppeals]=useState<Appeal[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState("");
 async function load(){const r=await fetch("/api/moderation/review");const d=await r.json();if(!r.ok){setError(d.error??"Unable to load moderation queue.");return;}setAppeals(d.appeals??[]);}
 useEffect(()=>{load()},[]);
 async function decide(id:string,status:"accepted"|"rejected"){const resolution=window.prompt(status==="accepted"?"Explain why the appeal is accepted and what evidence was verified.":"Explain why the restriction remains in place.");if(!resolution||resolution.trim().length<10)return;setBusy(id);const r=await fetch("/api/moderation/review",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({appealId:id,status,resolution})});const d=await r.json();setBusy("");if(!r.ok){setError(d.error??"Decision failed.");return;}await load();}
 return <main className="mx-auto max-w-6xl px-6 py-10"><div className="mb-8"><small>MODERATION CONTROL · PHASE 29</small><h1 className="text-3xl font-semibold">Appeals & dispute resolution</h1><p className="mt-2 text-white/50">Review restricted marketplace cases with an auditable decision and resolution.</p></div>{error&&<div className="mb-4 rounded-xl border border-rose-400/20 bg-rose-400/5 p-3 text-sm text-rose-200">{error}</div>}<div className="space-y-4">{appeals.length===0?<div className="hh-panel text-white/45">No appeals are currently waiting for review.</div>:appeals.map(a=><section key={a.id} className="hh-panel"><div className="flex flex-wrap items-center justify-between gap-3"><div><small className="text-white/40">CASE {a.case_id.slice(0,8)}</small><h2 className="text-lg">{a.status.toUpperCase()}</h2></div><span className="text-xs text-white/40">{new Date(a.submitted_at).toLocaleString()}</span></div><p className="mt-4 text-sm text-white/70">{a.reason}</p>{["submitted","under_review"].includes(a.status)&&<div className="mt-4 flex gap-2"><button disabled={busy===a.id} onClick={()=>decide(a.id,"accepted")} className="rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-100">Accept & reinstate</button><button disabled={busy===a.id} onClick={()=>decide(a.id,"rejected")} className="rounded-lg border border-rose-400/20 bg-rose-400/10 px-3 py-2 text-xs text-rose-100">Reject appeal</button></div>}</section>)}</div></main>
}