"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

export default function ProfilePage(){
 const router=useRouter(); const [role,setRole]=useState("Finance Manager"); const [skills,setSkills]=useState("FP&A, financial analysis, forecasting, Excel"); const [experience,setExperience]=useState("6"); const [country,setCountry]=useState("India"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage(""); const r=await fetch("/api/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({role,skills:skills.split(",").map(s=>s.trim()).filter(Boolean),experience:Number(experience),country})}); const d=await r.json(); if(!r.ok)setMessage(d.error||"Could not save"); else {setMessage("Profile saved. HiddenHire can now use it for matching."); setTimeout(()=>router.push("/dashboard"),500)} setBusy(false);}
 return <main className="min-h-screen px-5 py-10 sm:px-8"><div className="mx-auto max-w-3xl pt-10"><a href="/dashboard" className="text-sm text-cyan-300">← Dashboard</a><div className="search-panel mt-6"><div className="section-kicker">CAREER PROFILE</div><h1 className="mt-2 text-3xl font-semibold">Teach HiddenHire your career</h1><form onSubmit={save} className="mt-7 grid gap-5 md:grid-cols-2"><Field label="Target role"><input value={role} onChange={e=>setRole(e.target.value)} required/></Field><Field label="Skills"><input value={skills} onChange={e=>setSkills(e.target.value)}/></Field><Field label="Experience"><input type="number" min="0" value={experience} onChange={e=>setExperience(e.target.value)}/></Field><Field label="Country"><input value={country} onChange={e=>setCountry(e.target.value)}/></Field><div className="md:col-span-2">{message&&<p className="mb-4 text-sm text-white/60">{message}</p>}<button className="primary-button" disabled={busy}>{busy?"Saving…":"Save career profile"} <span>→</span></button></div></form></div></div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="text-xs font-medium uppercase tracking-[0.12em] text-white/40">{label}<div className="mt-2">{children}</div></label>}
