"use client";
import { useEffect,useState } from "react";
type Task={id:string;action:string;state:string;title:string;summary:string;requires_approval:boolean;attempts:number};
export default function CareerAgentExecution(){
 const [tasks,setTasks]=useState<Task[]>([]);
 async function load(){const r=await fetch("/api/career-execution/tasks");const d=await r.json();if(r.ok)setTasks(d.tasks??[]);}
 useEffect(()=>{load()},[]);
 async function transition(task:Task,event:string){await fetch("/api/career-execution/tasks",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({taskId:task.id,event})});await load();}
 return <section id="execution-control" className="hh-panel"><div className="hh-panel-heading"><div><small>AGENT EXECUTION · PHASE 30</small><h2>Approval-gated autonomous actions</h2></div><span>HUMAN CONTROL</span></div><p className="text-sm text-white/50">HiddenHire can prepare and queue career work autonomously, but final applications and communications remain under your approval.</p><div className="mt-4 space-y-3">{tasks.length===0?<p className="text-sm text-white/35">No execution tasks queued.</p>:tasks.slice(0,8).map(t=><div key={t.id} className="rounded-xl border border-white/10 bg-black/15 p-4"><div className="flex justify-between gap-3"><div><strong>{t.title}</strong><p className="mt-1 text-xs text-white/45">{t.summary}</p></div><span className="text-xs text-white/45">{t.state.replace("_"," ")}</span></div><div className="mt-3 flex gap-2">{t.state==="awaiting_approval"&&<button onClick={()=>transition(t,"approve")} className="rounded-lg border border-cyan-400/20 px-3 py-1.5 text-xs text-cyan-100">Approve</button>}{t.state==="approved"&&<button onClick={()=>transition(t,"start")} className="rounded-lg border border-cyan-400/20 px-3 py-1.5 text-xs text-cyan-100">Start</button>}{t.state==="executing"&&<button onClick={()=>transition(t,"complete")} className="rounded-lg border border-emerald-400/20 px-3 py-1.5 text-xs text-emerald-100">Mark complete</button>}{!["completed","cancelled"].includes(t.state)&&<button onClick={()=>transition(t,"cancel")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-white/55">Cancel</button>}</div></div>)}</div></section>;
}
