"use client";
import { useMemo } from "react";
import type { MatchResult } from "@/lib/job-types";
import { buildProactiveCareerPlan } from "@/lib/proactive-career-agent";
type Props = { matches: MatchResult[]; applications: Array<{ status: string; created_at: string }> };
const labels = { prepare: "PREPARE", follow_up: "FOLLOW UP", apply_now: "APPLY NOW", review: "REVIEW", watch: "WATCH", improve_profile: "PROFILE" } as const;
export default function ProactiveCareerPlan({ matches, applications }: Props) {
  const plan = useMemo(() => buildProactiveCareerPlan(matches, applications), [matches, applications]);
  const primary = plan.primary;
  return <section className="border-b border-white/10 px-5 py-4 sm:px-6"><div className="rounded-xl border border-cyan-300/15 bg-cyan-300/[.03] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-300">Agent orchestration</p><h3 className="mt-1 text-base font-semibold text-white">{plan.headline}</h3><p className="mt-1 max-w-2xl text-[11px] leading-5 text-white/50">{plan.summary}</p></div>{primary && <div className="rounded-lg border border-white/10 bg-black/10 px-3 py-2 text-right"><span className="block text-[9px] uppercase tracking-wider text-white/35">Agent confidence</span><strong className="block text-lg text-cyan-100">{primary.confidence}%</strong></div>}</div>{primary && <div className="mt-4 grid gap-3 lg:grid-cols-[1.4fr_1fr]"><div className="rounded-lg border border-cyan-300/10 bg-black/10 p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-xs font-semibold text-white">{primary.title}</p><p className="truncate text-[10px] text-white/40">{primary.company} · {primary.location}</p></div><span className="shrink-0 rounded-full border border-cyan-300/15 px-2 py-1 text-[8px] font-bold text-cyan-100">{labels[primary.action]}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-md border border-white/8 bg-black/10 p-2"><span className="block text-[8px] uppercase tracking-wider text-white/30">Match</span><strong className="text-sm text-white">{primary.score}%</strong></div><div className="rounded-md border border-white/8 bg-black/10 p-2"><span className="block text-[8px] uppercase tracking-wider text-white/30">Urgency</span><strong className="text-sm text-white">{primary.urgency}</strong></div></div><p className="mt-3 text-[10px] leading-5 text-white/60"><span className="font-semibold text-cyan-200">Why now:</span> {primary.whyNow}</p><p className="mt-1 text-[10px] leading-5 text-white/60"><span className="font-semibold text-cyan-200">Next:</span> {primary.nextStep}</p></div><div><p className="mb-2 text-[9px] font-semibold uppercase tracking-[.18em] text-white/35">Ranked actions</p><div className="space-y-2">{plan.items.map((item, index) => <a key={item.company + item.title} href={item.applicationUrl} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-lg border border-white/8 bg-black/10 px-3 py-2 hover:border-cyan-300/15"><span className="text-[9px] font-semibold text-cyan-200/70">0{index + 1}</span><span className="min-w-0 flex-1 truncate text-[10px] text-white/70">{item.title}</span><span className="shrink-0 text-[8px] font-bold text-white/40">{labels[item.action]}</span></a>)}</div></div></div>}{!primary && <p className="mt-3 text-[10px] text-white/40">The agent needs a fresh market signal before it can recommend a concrete action.</p>}</div></section>;
}