import type { CompanySourceProfile } from './job-source';

// Board identifiers were verified against the public Greenhouse jobs endpoint.
export const verifiedCompanyRegistry: CompanySourceProfile[] = [
  { companyName: 'Stripe', companyWebsite: 'https://stripe.com', careersUrl: 'https://boards.greenhouse.io/stripe', ats: 'greenhouse', boardIdentifier: 'stripe', country: 'United States', industries: ['Finance', 'Technology'], remotePolicy: 'Distributed teams with role-specific location requirements' },
  { companyName: 'Airtable', companyWebsite: 'https://www.airtable.com', careersUrl: 'https://boards.greenhouse.io/airtable', ats: 'greenhouse', boardIdentifier: 'airtable', country: 'United States', industries: ['Technology', 'Operations'], remotePolicy: 'Role-specific' },
  { companyName: 'Coinbase', companyWebsite: 'https://www.coinbase.com', careersUrl: 'https://boards.greenhouse.io/coinbase', ats: 'greenhouse', boardIdentifier: 'coinbase', country: 'United States', industries: ['Finance', 'Technology'], remotePolicy: 'Remote-first with location restrictions by role' },
  { companyName: 'Figma', companyWebsite: 'https://www.figma.com', careersUrl: 'https://boards.greenhouse.io/figma', ats: 'greenhouse', boardIdentifier: 'figma', country: 'United States', industries: ['Technology', 'Design'], remotePolicy: 'Role-specific' },
  { companyName: 'Datadog', companyWebsite: 'https://www.datadoghq.com', careersUrl: 'https://boards.greenhouse.io/datadog', ats: 'greenhouse', boardIdentifier: 'datadog', country: 'United States', industries: ['Technology', 'Data'], remotePolicy: 'Role-specific' },
  { companyName: 'GitLab', companyWebsite: 'https://about.gitlab.com', careersUrl: 'https://boards.greenhouse.io/gitlab', ats: 'greenhouse', boardIdentifier: 'gitlab', country: 'United States', industries: ['Technology', 'Engineering'], remotePolicy: 'All-remote with role-specific eligibility' },
  { companyName: 'Asana', companyWebsite: 'https://asana.com', careersUrl: 'https://boards.greenhouse.io/asana', ats: 'greenhouse', boardIdentifier: 'asana', country: 'United States', industries: ['Technology', 'Operations'], remotePolicy: 'Role-specific' },
  { companyName: 'Lyft', companyWebsite: 'https://www.lyft.com', careersUrl: 'https://boards.greenhouse.io/lyft', ats: 'greenhouse', boardIdentifier: 'lyft', country: 'United States', industries: ['Technology', 'Operations'], remotePolicy: 'Role-specific' },
  { companyName: 'Brex', companyWebsite: 'https://www.brex.com', careersUrl: 'https://boards.greenhouse.io/brex', ats: 'greenhouse', boardIdentifier: 'brex', country: 'United States', industries: ['Finance', 'Technology'], remotePolicy: 'Role-specific' },
  { companyName: 'Faire', companyWebsite: 'https://www.faire.com', careersUrl: 'https://boards.greenhouse.io/faire', ats: 'greenhouse', boardIdentifier: 'faire', country: 'United States', industries: ['Commerce', 'Operations'], remotePolicy: 'Role-specific' },
  { companyName: 'Intercom', companyWebsite: 'https://www.intercom.com', careersUrl: 'https://boards.greenhouse.io/intercom', ats: 'greenhouse', boardIdentifier: 'intercom', country: 'United States', industries: ['Technology', 'Sales'], remotePolicy: 'Role-specific' },
  { companyName: 'Okta', companyWebsite: 'https://www.okta.com', careersUrl: 'https://boards.greenhouse.io/okta', ats: 'greenhouse', boardIdentifier: 'okta', country: 'United States', industries: ['Technology', 'Security'], remotePolicy: 'Role-specific' },
  { companyName: 'Twilio', companyWebsite: 'https://www.twilio.com', careersUrl: 'https://boards.greenhouse.io/twilio', ats: 'greenhouse', boardIdentifier: 'twilio', country: 'United States', industries: ['Technology', 'Engineering'], remotePolicy: 'Role-specific' },
  { companyName: 'HubSpot', companyWebsite: 'https://www.hubspot.com', careersUrl: 'https://boards.greenhouse.io/hubspot', ats: 'greenhouse', boardIdentifier: 'hubspot', country: 'United States', industries: ['Technology', 'Marketing', 'Sales'], remotePolicy: 'Role-specific' },
  { companyName: 'Discord', companyWebsite: 'https://discord.com', careersUrl: 'https://boards.greenhouse.io/discord', ats: 'greenhouse', boardIdentifier: 'discord', country: 'United States', industries: ['Technology', 'Marketing'], remotePolicy: 'Role-specific' },
  { companyName: 'Duolingo', companyWebsite: 'https://www.duolingo.com', careersUrl: 'https://boards.greenhouse.io/duolingo', ats: 'greenhouse', boardIdentifier: 'duolingo', country: 'United States', industries: ['Technology', 'Education'], remotePolicy: 'Role-specific' },
  { companyName: 'Cloudflare', companyWebsite: 'https://www.cloudflare.com', careersUrl: 'https://boards.greenhouse.io/cloudflare', ats: 'greenhouse', boardIdentifier: 'cloudflare', country: 'United States', industries: ['Technology', 'Engineering'], remotePolicy: 'Role-specific' },
  { companyName: 'Dropbox', companyWebsite: 'https://www.dropbox.com', careersUrl: 'https://boards.greenhouse.io/dropbox', ats: 'greenhouse', boardIdentifier: 'dropbox', country: 'United States', industries: ['Technology', 'Operations'], remotePolicy: 'Virtual-first with role-specific eligibility' },
  { companyName: 'MongoDB', companyWebsite: 'https://www.mongodb.com', careersUrl: 'https://boards.greenhouse.io/mongodb', ats: 'greenhouse', boardIdentifier: 'mongodb', country: 'United States', industries: ['Technology', 'Data'], remotePolicy: 'Role-specific' },
  { companyName: 'Reddit', companyWebsite: 'https://www.reddit.com', careersUrl: 'https://boards.greenhouse.io/reddit', ats: 'greenhouse', boardIdentifier: 'reddit', country: 'United States', industries: ['Technology', 'Marketing'], remotePolicy: 'Role-specific' },
  { companyName: 'Samsara', companyWebsite: 'https://www.samsara.com', careersUrl: 'https://boards.greenhouse.io/samsara', ats: 'greenhouse', boardIdentifier: 'samsara', country: 'United States', industries: ['Technology', 'Operations'], remotePolicy: 'Role-specific' },
  { companyName: 'Toast', companyWebsite: 'https://pos.toasttab.com', careersUrl: 'https://boards.greenhouse.io/toast', ats: 'greenhouse', boardIdentifier: 'toast', country: 'United States', industries: ['Technology', 'Finance'], remotePolicy: 'Role-specific' },
  { companyName: 'Wikimedia Foundation', companyWebsite: 'https://wikimediafoundation.org', careersUrl: 'https://boards.greenhouse.io/wikimedia', ats: 'greenhouse', boardIdentifier: 'wikimedia', country: 'United States', industries: ['Technology', 'Operations'], remotePolicy: 'Remote-first with geographic requirements' },
  { companyName: 'Elastic', companyWebsite: 'https://www.elastic.co', careersUrl: 'https://boards.greenhouse.io/elastic', ats: 'greenhouse', boardIdentifier: 'elastic', country: 'United States', industries: ['Technology', 'Data'], remotePolicy: 'Distributed with role-specific eligibility' },
];
