import type { Job } from './job-types';

// Seed/demo data only. Replace with verified source data later.
export const seedJobs: Job[] = [
  {
    id: 'seed-finance-manager-1',
    title: 'Finance Manager',
    company: 'Northstar Capital',
    location: 'Remote',
    country: 'India',
    remote: true,
    indiaEligible: true,
    salaryMin: 45000,
    salaryMax: 60000,
    salaryCurrency: 'USD',
    employmentType: 'Full-time',
    industry: 'Finance',
    requiredSkills: ['Financial reporting', 'Reconciliation', 'AP/AR', 'Forecasting', 'Budgeting'],
    requiredExperience: 6,
    description: 'Lead monthly close activities, improve controls, and support strategic planning for a distributed finance team.',
    applicationUrl: 'https://example.com/jobs/northstar-finance-manager',
    source: 'SeedJobSource',
    postedDate: '2026-08-19',
  },
  {
    id: 'seed-data-analyst-1',
    title: 'Senior Data Analyst',
    company: 'Arc Labs',
    location: 'Remote',
    country: 'India',
    remote: true,
    indiaEligible: true,
    salaryMin: 52000,
    salaryMax: 70000,
    salaryCurrency: 'USD',
    employmentType: 'Full-time',
    industry: 'Analytics',
    requiredSkills: ['SQL', 'Python', 'Dashboarding', 'Data modeling', 'Stakeholder communication'],
    requiredExperience: 5,
    description: 'Build dashboards, monitor funnel performance, and translate business questions into analytical insights.',
    applicationUrl: 'https://example.com/jobs/arc-data-analyst',
    source: 'SeedJobSource',
    postedDate: '2026-08-27',
  },
  {
    id: 'seed-product-ops-1',
    title: 'Product Operations Manager',
    company: 'Harbor Cloud',
    location: 'Remote',
    country: 'United States',
    remote: true,
    indiaEligible: true,
    salaryMin: 50000,
    salaryMax: 68000,
    salaryCurrency: 'USD',
    employmentType: 'Full-time',
    industry: 'Technology',
    requiredSkills: ['Workflow design', 'Product analytics', 'KPI reporting', 'Cross-functional leadership'],
    requiredExperience: 4,
    description: 'Own operational processes, analytics and decision support for a global SaaS product organization.',
    applicationUrl: 'https://example.com/jobs/harbor-product-ops',
    source: 'SeedJobSource',
    postedDate: '2026-09-01',
  },
  {
    id: 'seed-hrbp-1',
    title: 'HR Business Partner',
    company: 'Summit Works',
    location: 'Bengaluru, India',
    country: 'India',
    remote: false,
    indiaEligible: true,
    salaryMin: 25000,
    salaryMax: 40000,
    salaryCurrency: 'INR',
    employmentType: 'Full-time',
    industry: 'Human Resources',
    requiredSkills: ['Employee relations', 'Policy design', 'Stakeholder management', 'Performance management'],
    requiredExperience: 5,
    description: 'Partner with leaders across engineering and operations to deliver employee experience and policy support.',
    applicationUrl: 'https://example.com/jobs/summit-hrbp',
    source: 'SeedJobSource',
    postedDate: '2026-08-22',
  },
  {
    id: 'seed-senior-accountant-1',
    title: 'Senior Accountant',
    company: 'Crestline Advisory',
    location: 'Remote',
    country: 'United Kingdom',
    remote: true,
    indiaEligible: true,
    salaryMin: 43000,
    salaryMax: 56000,
    salaryCurrency: 'USD',
    employmentType: 'Full-time',
    industry: 'Accounting',
    requiredSkills: ['General ledger', 'Month-end close', 'VAT', 'Financial controls', 'Excel'],
    requiredExperience: 4,
    description: 'Support financial reporting and operational controls for a remote-first finance organization.',
    applicationUrl: 'https://example.com/jobs/crestline-senior-accountant',
    source: 'SeedJobSource',
    postedDate: '2026-08-18',
  }
];
