import type { Job } from "./types";

export const demoJobs: Job[] = [
  {
    id: "demo-coinbase-finance",
    title: "Finance Manager, Strategic Finance",
    company: "Coinbase",
    location: "Remote — India eligible",
    remote: true, indiaEligible: true,
    salaryMin: 45000, salaryMax: 70000, currency: "USD",
    source: "Company careers", url: "https://www.coinbase.com/careers",
    posted: "Recently listed",
    description: "Own forecasting, management reporting, financial analysis and strategic planning across a global finance organization.",
    skills: ["FP&A", "financial analysis", "forecasting", "Excel", "finance"],
  },
  {
    id: "demo-twilio-finance",
    title: "Senior Financial Analyst",
    company: "Twilio",
    location: "Remote — India eligible",
    remote: true, indiaEligible: true,
    salaryMin: 38000, salaryMax: 60000, currency: "USD",
    source: "Company careers", url: "https://www.twilio.com/company/jobs",
    posted: "Recently listed",
    description: "Partner with business leaders on budgeting, forecasting, variance analysis and financial reporting.",
    skills: ["FP&A", "budgeting", "forecasting", "financial reporting", "Excel"],
  },
  {
    id: "demo-okta-fpa",
    title: "Manager, Financial Planning & Analysis",
    company: "Okta",
    location: "Remote — India eligible",
    remote: true, indiaEligible: true,
    salaryMin: 50000, salaryMax: 80000, currency: "USD",
    source: "Company careers", url: "https://www.okta.com/company/careers/",
    posted: "Recently listed",
    description: "Lead planning cycles, management reporting, scenario analysis and cross-functional finance projects.",
    skills: ["FP&A", "scenario analysis", "forecasting", "finance", "reporting"],
  },
  {
    id: "demo-samsara-accounting",
    title: "Finance Operations Manager",
    company: "Samsara",
    location: "Remote — India eligible",
    remote: true, indiaEligible: true,
    salaryMin: 42000, salaryMax: 65000, currency: "USD",
    source: "Company careers", url: "https://www.samsara.com/company/careers",
    posted: "Recently listed",
    description: "Manage finance operations, close processes, controls, reconciliations and operational analytics.",
    skills: ["accounting", "finance operations", "reconciliation", "controls", "Excel"],
  },
];